# Generated by Django 4.2 on 2024-02-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Neighborhoods",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "neighborhoods",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RealEstateProperties",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("padctn_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("map_parcel", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "map_parcel_trimmed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mailing_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "property_use",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("zone", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("neighborhood", models.IntegerField(blank=True, null=True)),
                (
                    "square_footage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_update_date", models.DateField(blank=True, null=True)),
                (
                    "neighborhoods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.neighborhoods",
                    ),
                ),
            ],
            options={
                "db_table": "real_estate_properties",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TnDavidsonAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True, db_column="Longitude", max_length=200, null=True
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True, db_column="Latitude", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tn_davidson_addresses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RealEstateSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField(blank=True, null=True)),
                (
                    "sale_price",
                    models.CharField(
                        blank=True,
                        db_collation="utf8_general_ci",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "real_estate_properties",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dashboard.realestateproperties",
                    ),
                ),
            ],
            options={
                "db_table": "real_estate_sales",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="realestateproperties",
            name="tn_davidson_addresses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dashboard.tndavidsonaddresses",
            ),
        ),
    ]
